version: '3'

services:
  django:
    build:
      context: ./
      dockerfile: docker/Dockerfile.prod
    entrypoint: /django/entrypoint.prod.sh
    env_file:
      - env_conf/.prod.env
    expose:
      - 8000
    volumes:
      - static_volume:/django/static
      - media_volume:/django/media
    depends_on:
      - db

  celery:
    build:
      context: ./
      dockerfile: docker/Dockerfile.prod
    command: poetry run celery --app config worker -l INFO
    env_file:
      - env_conf/.prod.env
    depends_on:
      - db
      - redis

  db:
    image: postgres:14-alpine
    volumes:
      - pg-data:/var/lib/postgresql/data/
    env_file:
      - env_conf/.prod.db.env

  redis:
    image: redis:6.2.6-alpine
    command: redis-server --requirepass ${REDIS_PASSWORD}
    ports:
      - 6379:6379
    volumes:
      - redis-data:/data

  nginx:
    build: ./nginx
    ports:
      - 8000:80
    volumes:
      - static_volume:/django/static
      - media_volume:/django/media
    depends_on:
      - django

volumes:
  pg-data:
  redis-data:
  static_volume:
  media_volume:
