version: '3'

services:
  django:
    build: 
      context: './src'
      dockerfile: Dockerfile.prod
    command: poetry run gunicorn config.wsgi:application -c config/gunicorn.conf.py --bind 0.0.0.0:8000
    env_file:
      - ./.env.prod
    expose:
      - 8000
    volumes:
      - static_volume:/django/static
      - media_volume:/django/media
    depends_on:
      - db

  celery:
    build: 
      context: './src'
      dockerfile: Dockerfile.prod
    command: poetry run celery --app config worker -l INFO
    env_file:
      - ./.env.prod
    depends_on:
      - db
      - redis

  db:
    image: postgres:14-alpine
    volumes:
      - pg-data:/var/lib/postgresql/data/
    env_file:
      - ./.env.prod.db
  
  redis:
    image: redis:6.2.6-alpine
    ports:
      - 6379:6379
    volumes:
      - redis-data:/data

  nginx:
    build: ./nginx
    ports:
      - 8000:80
    volumes:
      - static_volume:/django/static
      - media_volume:/django/media
    depends_on:
      - django

volumes:
  pg-data:
  redis-data:
  static_volume:
  media_volume: