version: '3'

services:
  django:
    build: './src'
    command: poetry run python manage.py runserver 0.0.0.0:8000
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
    depends_on:
      - db
      - redis

  celery:
    build: './src'
    command: poetry run celery --app config worker -l INFO
    env_file:
      - ./.env.dev
    depends_on:
      - db
      - redis

  db:
    image: postgres:14-alpine
    volumes:
      - pg-data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=pass
      - POSTGRES_DB=database

  redis:
    image: redis:6.2.6-alpine
    ports:
      - 6379:6379
    volumes:
      - redis-data:/data

volumes:
  pg-data:
  redis-data:
