# Generated by Django 4.0 on 2021-12-14 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_customuser_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='two_fa_type',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Email'), (2, 'Phone')], null=True),
        ),
    ]
