# Generated by Django 4.0 on 2021-12-25 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_verificationcode_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='verified',
            new_name='is_verified',
        ),
        migrations.AddField(
            model_name='verificationcode',
            name='jwt_jti',
            field=models.CharField(default='dummyjti', max_length=32),
            preserve_default=False,
        ),
    ]
