# Generated by Django 4.0 on 2021-12-25 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_rename_verified_customuser_is_verified_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='verificationcode',
            old_name='used',
            new_name='is_used',
        ),
    ]
