# Generated by Django 4.0 on 2021-12-12 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_customuser_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='two_fa_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customuser',
            name='two_fa_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Email'), (2, 'Phone')], null=True),
        ),
    ]
